# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fa42c454f95dba217bc3b195864e89feb3922738211cddd0ac258530679f13cfe5fa543e5846f9208a28a535a062cd3e1dd91164a915b93038ab4f9fbb18f8

test:
  secret_key_base: 8328dcb816d976f6d8da596992db3cd9ac29c8ae6c63ae71385f1bbf27fd25ddf1abc1fdd54b926a73fb79950bc09a58aff5f99bcf43c54a5f01da39992bd29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
